/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Sockets.Controleur;
import Objets.Avion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Firass Semaan
 */
public class CtrlInterface extends javax.swing.JFrame {

    Controleur _socketClient = null;
    private int _flightId;

    public CtrlInterface() {
        initComponents();
        this.setSize(800, 600);
        this.setTitle("Controller...");
        this.setLocationRelativeTo(null);
        _socketClient = new Controleur(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        lstVols = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        lstVols.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstVolsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstVols);

        getContentPane().add(jScrollPane3, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (_socketClient != null) {
            _socketClient.fermer_communication();
        }
    }//GEN-LAST:event_formWindowClosing

    private void lstVolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstVolsMouseClicked
        if (_socketClient._detectedFlights == null) {
            return;
        }

        String item = lstVols.getSelectedValue();
        if (item != null && !item.isEmpty()) {

            String flightName = item.substring(9, 14);
            Avion av = null;
            for (int i = 0; i < _socketClient._detectedFlights.size(); i++) {
                if (_socketClient._detectedFlights.get(i).getFlightName().equals(flightName)) {
                    av = _socketClient._detectedFlights.get(i);
                    break;
                }
            }
            if (av == null) {
                return;
            }
            //String flightName = av.getFlightName();
            Object cap = av.getDeplacement().getCap();
            Object alt = av.getPosition().getAltitude();
            Object vit = av.getDeplacement().getVitesse();
            _flightId = av.getFlightId();
            VolManagementInterface frame = new VolManagementInterface(_socketClient, _flightId, alt.toString(), cap.toString(), vit.toString());
            frame.setTitle(av.getFlightName());
            frame.setAlwaysOnTop(true);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.setVisible(true);

        }

    }//GEN-LAST:event_lstVolsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println("Look & Feel exception");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CtrlInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList<String> lstVols;
    // End of variables declaration//GEN-END:variables
}
